# Generated by packaging/render-manifests.sh from packaging/homebrew/relayweft.rb.tmpl.
# The formula is named relayweft and installs the rw command. It uses the
# release binaries, so it needs no bottles and no Go.
class Relayweft < Formula
  desc "Terminal app that routes coding work between the Codex CLI and Claude Code"
  homepage "https://github.com/sparkz400/relayweft"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.4.0/rw-darwin-arm64"
      sha256 "a859dbffc58be99a6bc6d220505c6995ba3586f3d83c795f25617aa3fee3078a"
    end
    on_intel do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.4.0/rw-darwin-amd64"
      sha256 "664cb40a9deb98717e98ae0a9cfe7d3de3080ca1df22ce9c890639ae629f454f"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.4.0/rw-linux-arm64"
      sha256 "06ec4f60b076fb1e07bbde21a128ee15f1b4044846db63bb0915da7570961276"
    end
    on_intel do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.4.0/rw-linux-amd64"
      sha256 "5142e3b15fa70284593d61bbfa87b58a0fe5382de0560ef4ab792926d55735e9"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "rw-#{os}-#{arch}" => "rw"
    # Make the raw download executable before generating completion.
    chmod 0755, bin/"rw"
    generate_completions_from_executable(bin/"rw", "completion")
  end

  def caveats
    <<~EOS
      Run `rw doctor` to check the codex and claude CLIs.
      Update with `brew upgrade relayweft`.
    EOS
  end

  test do
    assert_equal "relayweft #{version}", shell_output("#{bin}/rw version").strip
    assert_path_exists bash_completion/"rw"
    assert_path_exists zsh_completion/"_rw"
    assert_path_exists fish_completion/"rw.fish"
  end
end
