# Generated by packaging/render-manifests.sh from packaging/homebrew/relayweft.rb.tmpl.
# The formula is named relayweft and installs the rw command. It uses the
# release binaries, so it needs no bottles and no Go.
class Relayweft < Formula
  desc "Terminal app that routes coding work between the Codex CLI and Claude Code"
  homepage "https://github.com/sparkz400/relayweft"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.3.0/rw-darwin-arm64"
      sha256 "d0cdec8d4a50346ddd1c9a5a2ac37aa3f59759d1a72b03332b1316fd17d55329"
    end
    on_intel do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.3.0/rw-darwin-amd64"
      sha256 "9d97104d3d82818152215bc893d6bb568a23de19968e8a73d057fdf6358dfc3e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.3.0/rw-linux-arm64"
      sha256 "2a65fa42c4f61b0b3a7e99cd301d03d50233d80ddb8d869e61ca2d1e2937a0e8"
    end
    on_intel do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.3.0/rw-linux-amd64"
      sha256 "610a21696b116519b592ce1a0a3f2f2ab4515f66ee442e6535f1d1d7d6158784"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "rw-#{os}-#{arch}" => "rw"
    # `rw completion` arrived in v0.4.0.
    generate_completions_from_executable(bin/"rw", "completion") if version >= "0.4.0"
  end

  def caveats
    <<~EOS
      Run `rw doctor` to check the codex and claude CLIs.
      Update with `brew upgrade relayweft`.
    EOS
  end

  test do
    assert_equal "relayweft #{version}", shell_output("#{bin}/rw version").strip
  end
end
