# Generated by packaging/render-manifests.sh from packaging/homebrew/relayweft.rb.tmpl.
# The formula is named relayweft and installs the rw command. It uses the
# release binaries, so it needs no bottles and no Go.
class Relayweft < Formula
  desc "Terminal app that routes coding work between the Codex CLI and Claude Code"
  homepage "https://github.com/sparkz400/relayweft"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.2.0/rw-darwin-arm64"
      sha256 "0ea4bf554df324bfc3020804098ee097f6c35640351c6c00c1a8fb432041b747"
    end
    on_intel do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.2.0/rw-darwin-amd64"
      sha256 "9556c5529ddde942be22a4481749cb33669ba4152544f208b92dce17accfb3c1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.2.0/rw-linux-arm64"
      sha256 "4ff5f1019ea073adf30413c6d30976e312c9a9c08caa768a48330208efbd93ce"
    end
    on_intel do
      url "https://github.com/sparkz400/relayweft/releases/download/v0.2.0/rw-linux-amd64"
      sha256 "886463cc07f297a261d1ea2e22e0af9c451fab7f6839a60a2066db2365c137f2"
    end
  end

  def install
    os = OS.mac? ? "darwin" : "linux"
    arch = Hardware::CPU.arm? ? "arm64" : "amd64"
    bin.install "rw-#{os}-#{arch}" => "rw"
  end

  def caveats
    <<~EOS
      Run `rw doctor` to check the codex and claude CLIs.
      Update with `brew upgrade relayweft`.
    EOS
  end

  test do
    assert_equal "relayweft #{version}", shell_output("#{bin}/rw version").strip
  end
end
