#!/bin/sh
# Fills the package manifests for a published release.
#
#   packaging/render-manifests.sh 1.2.3 [checksums.txt] [winget-out-dir]
#
# Without a checksums file it downloads the release's checksums.txt with
# the gh CLI. It updates in place (commit these):
#   - packaging/scoop/rw.json
#   - Formula/relayweft.rb (the Homebrew tap) from packaging/homebrew/
#   - packaging/aur/PKGBUILD and .SRCINFO from their templates
# and writes the rendered winget manifests to winget-out-dir (default:
# ./winget-out/<version>), ready for a microsoft/winget-pkgs pull request.
set -eu

version="${1:?usage: render-manifests.sh VERSION [checksums.txt] [out-dir]}"
version="${version#v}"
case "$version" in
  *-*)
    echo "$version is a pre-release; the manifests only follow releases" >&2
    exit 1
    ;;
esac
here="$(cd "$(dirname "$0")" && pwd)"
root="$(dirname "$here")"
sums="${2:-}"
out="${3:-winget-out/$version}"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
if [ -z "$sums" ]; then
  gh release download "v$version" --repo sparkz400/relayweft --pattern checksums.txt --dir "$tmp"
  sums="$tmp/checksums.txt"
fi

hash_of() {
  h="$(awk -v n="$1" '{ f=$2; sub(/^\*/, "", f); if (f == n) print $1 }' "$sums")"
  if [ -z "$h" ]; then
    echo "no checksum for $1 in $sums" >&2
    exit 1
  fi
  echo "$h"
}
sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{ print $1 }'
  else
    shasum -a 256 "$1" | awk '{ print $1 }'
  fi
}
x64="$(hash_of rw-windows-amd64.exe)"
arm64="$(hash_of rw-windows-arm64.exe)"
darwin_amd64="$(hash_of rw-darwin-amd64)"
darwin_arm64="$(hash_of rw-darwin-arm64)"
linux_amd64="$(hash_of rw-linux-amd64)"
linux_arm64="$(hash_of rw-linux-arm64)"

# The AUR package also ships the license and README of the tagged commit,
# downloaded the same way makepkg will.
for f in LICENSE README.md; do
  curl -fsSL --retry 3 -o "$tmp/$f" "https://raw.githubusercontent.com/sparkz400/relayweft/v$version/$f"
done
license="$(sha256 "$tmp/LICENSE")"
readme="$(sha256 "$tmp/README.md")"

# The release's own date, not today's: rendering can happen days later.
today="$(gh release view "v$version" --repo sparkz400/relayweft --json publishedAt -q .publishedAt 2>/dev/null | cut -c1-10 || true)"
[ -n "$today" ] || today="$(date -u +%Y-%m-%d)"

# render TEMPLATE OUTPUT [HEADER]: fills the {{...}} fields and replaces
# the template's "# Template:" line with HEADER (or drops it).
render() {
  sed -e "s|^# Template:.*|${3:-}|" \
    -e "s|{{VERSION}}|$version|g" \
    -e "s|{{SHA256_X64}}|$x64|g" \
    -e "s|{{SHA256_ARM64}}|$arm64|g" \
    -e "s|{{SHA256_DARWIN_AMD64}}|$darwin_amd64|g" \
    -e "s|{{SHA256_DARWIN_ARM64}}|$darwin_arm64|g" \
    -e "s|{{SHA256_LINUX_AMD64}}|$linux_amd64|g" \
    -e "s|{{SHA256_LINUX_ARM64}}|$linux_arm64|g" \
    -e "s|{{SHA256_LICENSE}}|$license|g" \
    -e "s|{{SHA256_README}}|$readme|g" \
    -e "s|{{RELEASE_DATE}}|$today|g" \
    "$1" | tr -d '\r' > "$2.tmp"
  # An empty header leaves an empty first line; drop it.
  if [ -z "${3:-}" ]; then
    sed -e '1{/^$/d;}' "$2.tmp" > "$2"
    rm -f "$2.tmp"
  else
    mv "$2.tmp" "$2"
  fi
  if grep -q '{{' "$2"; then
    echo "unfilled field in $2" >&2
    exit 1
  fi
}

# Scoop: the manifest's layout is fixed, so line-based edits are safe.
scoop="$here/scoop/rw.json"
sed -i.bak \
  -e "s|\"version\": \"[^\"]*\"|\"version\": \"$version\"|" \
  -e "s|/download/v[^/\$]*/rw-windows|/download/v$version/rw-windows|" \
  "$scoop"
# Each hash line follows its url line; replace them in order (x64, arm64).
awk -v a="$x64" -v b="$arm64" '
  /"hash": "[0-9a-fA-F]+"/ { n++; sub(/"hash": "[0-9a-fA-F]+"/, "\"hash\": \"" (n == 1 ? a : b) "\"") }
  { print }
' "$scoop" > "$scoop.tmp"
mv "$scoop.tmp" "$scoop"
rm -f "$scoop.bak"

mkdir -p "$root/Formula"
render "$here/homebrew/relayweft.rb.tmpl" "$root/Formula/relayweft.rb" \
  "# Generated by packaging/render-manifests.sh from packaging/homebrew/relayweft.rb.tmpl."
render "$here/aur/PKGBUILD.tmpl" "$here/aur/PKGBUILD"
render "$here/aur/SRCINFO.tmpl" "$here/aur/.SRCINFO"

mkdir -p "$out"
for f in "$here"/winget/*.yaml; do
  render "$f" "$out/$(basename "$f")"
done

echo "updated $scoop"
echo "updated $root/Formula/relayweft.rb"
echo "updated $here/aur/PKGBUILD and .SRCINFO"
echo "wrote winget manifests to $out"
